% -*- mode: noweb;noweb-font-lock-mode: R-mode; -*-
%
% NOTE -- ONLY EDIT THE .Rnw FILE!!!  The .tex file is
% likely to be overwritten.
%
% \VignetteIndexEntry{aCGH Overview}
% \VignetteDepends{tools, aCGH}
% \VignetteKeywords{DNA Copy Number Analysis}
% \VignettePackage{aCGH}
\documentclass[11pt]{article}

\usepackage{amsmath,psfig,pstricks,fullpage}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}
\SweaveOpts{echo=FALSE}
\usepackage{a4wide}

\parindent 0in

\bibliographystyle{abbrvnat}

\begin{document}

\title{\bf Bioconductor's aCGH package}

\author{Jane Fridlyand$^1$ and Peter Dimitrov$^2$}

\maketitle

\begin{center}
1. Department of Epidemiology and Biostatistics, and Comprehensive Cancer Center, University of California, San Francisco, {\tt jfridlyand@cc.ucsf.edu}\\
2. Division of Biostatistics, University of California, Berkeley, {\tt dimitrov@stat.berkeley.edu}
\end{center}

\tableofcontents

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Overview}

This document presents an overview of the {\tt aCGH} package, which provides wide basic functions for reading, analyzing and plotting array Comparative Genomic Hybridization data (\cite{Snijdersetal01}). Specific example for reading data in is using output of the custom freely available programs, SPOT and SPROC (\cite{Jainetal02}). These programs provide image quantification and pre-processing.  Outputs of all the other image processing software need to be combined into a single file containing observed values for each clone and samples and then read in as a matrix. 

\section{Data}

The data used in the example was generated in in lab of Dr. Fred Waldman at UCSF Comprehensive Cancer Center (\cite{Nakaoetal04}).Array CGH has been done on 125 colorectal fresh-frozen primary tumors and the associations with various phenotypes were analyzed. To reduce running time, only 40 samples are used in the 
examples.

\section{Examples}

\subsection{Creating aCGH object from log2.ratios and clone info
files}

Each array CGH object has to contain the log2ratios reperesenting
relative copy number along with the mapping information including but
not limited to clone name, chromosome and kb relative to the
chromosome. Optionally there may be phenotypes associated with each
sample.

<<echo=TRUE,print=FALSE>>=
library(aCGH)
datadir <- system.file("data", package = "aCGH")
clones.info <-
      read.table(file = file.path(datadir, "clones.info.ex.csv"),
                 header = T, sep = "\t")
log2.ratios <-
      read.table(file = file.path(datadir, "log2.ratios.ex.csv"),
                 header = T, sep = "\t")
pheno.type <-
      read.table(file = file.path(datadir, "pheno.type.ex.csv"),
                 header = T, sep = "\t")
ex.acgh <- create.aCGH(log2.ratios, clones.info, pheno.type)
@
%%<<results=hide>>=
%%datadir <- system.file("data", package = "aCGH")
%%clones.info <-
%%      read.table(file = file.path(datadir, "clones.info.ex.csv"),
%%                 header = T, sep = "\t")
%%log2.ratios <-
%%      read.table(file = file.path(datadir, "log2.ratios.ex.csv"),
%%                 header = T, sep = "\t")
%%pheno.type <-
%%      read.table(file = file.path(datadir, "pheno.type.ex.csv"),
%%                 header = T, sep = "\t")
%%create.aCGH(log2.ratios, clones.info, pheno.type)

\subsection{Printing, summary and basic plotting
(fig. \ref{cap:Plot-clustered-samples}) for objects of class aCGH}

<<echo=TRUE,print=FALSE>>=
data(colorectal)
colorectal
summary(colorectal)
@

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plot(colorectal)
@
\end{center}
\caption{Basic plot of the clustered samples}
\label{cap:Plot-clustered-samples}
\end{figure}

<<echo=TRUE,print=FALSE>>=
sample.names(colorectal)
phenotype(colorectal)[1:4,]
@

\subsection{Reading Sproc files}

Here we demonstrate reading of the sproc files and combining them into
one array CGH object. Sproc file format is specific to the custom
SPROC processing software at UCSF Cancer Center.

<<echo=TRUE,print=FALSE>>=
datadir <- system.file("examples", package = "aCGH")
latest.mapping.file <-
	file.path(datadir, "human.clones.info.Jul03.csv")
ex.acgh <-
	aCGH.read.Sprocs(dir(path = datadir,
			pattern = paste("*", "txt", sep = "\."),
			full.names = TRUE), latest.mapping.file,
			chrom.remove.threshold = 23)
ex.acgh
@

\subsection{Basic plot for batch of aCGH Sproc
files. (fig. \ref{cap:Basic-plot})}

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plot(ex.acgh)
@
\end{center}
\caption{Basic plot for batch of aCGH Sproc files}
\label{cap:Basic-plot}
\end{figure}

\subsection{Subsetting example}

<<echo=TRUE,print=FALSE>>=
cr <- colorectal[ ,1:3]
@

\subsection{Basic plot for the ordered log2 ratios along the genome}

The relative copy number is plotted along the genome with clones
placed in the genomic order
(fig. \ref{cap:Basic-plot-ordered-log2-ratios}). Chromosome Y is
excluded.

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotGenome(ex.acgh, Y = FALSE)
@
\end{center}
\caption{Basic plot for the ordered log2 ratios along the genome}
\label{cap:Basic-plot-ordered-log2-ratios}
\end{figure}

\subsection{Plotting hmm states}

For a given sample, each chromosome is plotted on a separate page
along with its smoothed
values(fig. \ref{cap:Plotting-hmm-states}). The genomic events
such as transitions, focal aberrations and amplifications are
indicated. The outliers are also marked.

<<echo=TRUE,print=FALSE>>=
## Determining hmm states of the clones

hmm(ex.acgh) <- find.hmm.states(ex.acgh)

## Merging hmm states

hmm.merged(ex.acgh) <-
   mergeHmmStates(ex.acgh, model.use = 1, minDiff = .25)

## Calculating the standard deviations for each array. Standard error is 
##calculated for each region and then averaged across regions.

sd.samples(ex.acgh) <- computeSD.Samples(ex.acgh)

## Finding the genomic events associated with each sample using 
##results of the partitioning into the states.

genomic.events(ex.acgh) <- find.genomic.events(ex.acgh)

## Plotting and printing the hmm states either to the screen or into the 
##postscript file.

##postscript("hmm.states.temp.ps");plotHmmStates(ex.acgh, sample.ind=1);dev.off()
@

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotHmmStates(colorectal, sample.ind = 1, chr = 1)
@
\end{center}
\caption{Plotting the hmm states found for colorectal data set.}
\label{cap:Plotting-hmm-states}
\end{figure}

\subsection{Plotting summary of the tumor
profiles(fig. \ref{cap:Plotting-summary-tumor-profiles})}
Here the distribution of various genomic events as well as their
frequency by location is displayed.

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotSummaryProfile(colorectal)	
@
\end{center}
\caption{Plotting summary of the tumor profiles}
\label{cap:Plotting-summary-tumor-profiles}
\end{figure}

\subsection{Overall frequency plot
(fig. \ref{cap:Overall-frequency-plot})}

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotFreqStat(colorectal, all = T)
@
\end{center}
\caption{Overall frequency plot of the tumor profiles}
\label{cap:Overall-frequency-plot}
\end{figure}

summarize.clones() function is the text equivalent of plotFreqStat() -
it summarizes the frequencies of changes for each clone accross
tumors.

<<echo=TRUE,print=FALSE>>=
summarize.clones(colorectal)[1:10 ,]
@

%TkWidgets - later!!!

\subsection{Testing association of clones with categorical, censored
or continuous outcomes.}

Use mt.maxT function from multtest package to
test differences in group means for each clone grouped by sex. Plot
the result along the genome displaying the frequencies of gains and losses
as well well as height of the statistic correponsding to each
clone(figs. 6 and 7.). The p-value can be adjusted and the horizontal
lines indicate chosen level of significance.

<<echo=TRUE,print=FALSE>>=
colnames(phenotype(colorectal))
sex <- phenotype(colorectal)$sex
sex.na <- !is.na(sex)
colorectal.na <- colorectal[ ,sex.na ]
dat <- log2.ratios.imputed(colorectal.na)
resT.sex <- mt.maxT(dat, sex[sex.na], test = "t", B = 1000)
@

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotFreqStat(colorectal.na, resT.sex, sex[sex.na], titles =
             c("Female", "Male"), X = FALSE, Y = FALSE)
@
\end{center}
\caption{Frequency plots of the samples with respect to the sex groups}
\end{figure}

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotSummaryProfile(colorectal, response = sex,
                   titles = c("Female", "Male"),
                   X = FALSE, Y = FALSE, maxChrom = 22)
@
\end{center}
\caption{Plotting summary of the tumor profiles}
\end{figure}

Testing association of clones with censored outcomes.

<<echo=TRUE,print=FALSE>>=
time <- rexp(ncol(colorectal), rate = 1 / 12)
events <- rbinom(ncol(colorectal), size = 1, prob = .5)
surv.obj <- Surv(time, 	events)
surv.obj
stat.coxph <-
  aCGH.test(colorectal, surv.obj, test = "coxph",
	p.adjust.method = "fdr")
stat.coxph[1:20 ,]
@

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotFreqStat(colorectal, stat.coxph, events, titles =
             c("Survived/Censored", "Dead"), X = FALSE, Y = FALSE)
@
\end{center}
\caption{Frequency plots of the samples with respect to survival.}
\end{figure}

Deriving statistics and p-values for testing the linear association
of age with the log2 ratios of each clone along the tumors.

<<echo=TRUE,print=FALSE>>=
age <- phenotype(colorectal)$age
age.na <- which(!is.na(age))
age <- age[age.na]
colorectal.na <- colorectal[, age.na]
stat.age <-
  aCGH.test(colorectal.na, age, test = "linear.regression",
            p.adjust.method = "fdr")
stat.age[1:20 ,]
@

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotFreqStat(colorectal.na, stat.age, ifelse(age < 70, 0, 1), titles =
             c("Young", "Old"), X = FALSE, Y = FALSE)
@
\end{center}
\caption{Frequency plots of the samples with respect to age.}
\end{figure}

Here we create a resT object using the values derived above.

%<<echo=TRUE,print=FALSE>>=
%resT.age <- data.frame(index = 1:ncol(stat.age),
%                       teststat = stat.age[1,],
%                       rawp = stat.age[2,],
%                       adjp = p.adjust(stat.age[2,], "fdr"))
%resT.age <- resT.age[order(resT.age$adjp),]
%@
%%%\begin{figure}[ht]
%%%  \begin{center}
%%%<<fig=TRUE,echo=TRUE>>=
%%%plotFreqStat(colorectal.na, resT.age, age[age.na])
%%%@
%%%    \caption{Plotting summary of the tumor profiles}
%%%  \end{center}
%%%\end{figure}

\subsection{Clustering samples}

Here we cluster samples within each phenotype using chromosomes 4,
8 and 9 and display the phenotype labels, in this case, sex
(fig. \ref{cap:Clustering-samples-sex}).

\begin{figure}[ht]
\begin{center}
<<fig=TRUE,echo=TRUE>>=
plotvalGenome.func(colorectal, response = phenotype(colorectal)$sex,
		titles = c("Female", "Male"),
		byclass = TRUE, showaber = TRUE, vecchrom = c(4,8,9),
		dendPlot = FALSE, imp = FALSE)
@
\end{center}
\caption{Clustering of the samples by sex}
\label{cap:Clustering-samples-sex}
\end{figure}

%%\SweaveOpts{echo=true}

\section{Acknowledgements}

The authors would like to express their gratitude to Drs. Fred Waldman and Kshama Mehta for sharing the data and to Dr. Taku Tokuyasu for quantifying the images. This work would not be possible without generous support and advice of Drs. Donna Albertson, Dan Pinkel and Ajay Jain. Antoine Snijders has played an integral role in developing ideas leading to the algorithms implemented in this package.

\bibliography{aCGH}

\end{document}
